name: Fetch Sponsorships and Commit

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Sponsorships and Commit
        uses: santoshyadavdev/sponsorship-green-squares@main
        with:
          allow-add-to-readme: 'false' # Default value, set to 'true' to enable README updates
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          # do not use GITHUB_TOKEN as it lacks the permission to call graphql APIs,
          #create a new Personal Access TOKEN and provide read:org access to read to sponsorship data
